apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: adel-project
  namespace: argocd
spec:
  description: ArgoCD Project Adel
  sourceRepos:
    - 'https://git.winteraccess.id/adel/Employee-manifest.git'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'